# to run the server: uwsgi --ini uwsgi.ini

[uwsgi]

safe-pidfile = /tmp/ristomele.pid

virtualenv = /home/verde3/.pyenv/versions/venv
logto = /home/verde3/ristomele/log/%n.log

chdir = /home/verde3/ristomele
mount = /=server.app:create_logged_app()

master = true
processes = 1
threads = 2

#uid = pi
#gid = pi
uid = sta
gid = sta

https = 0.0.0.0:5000,/home/sta/ristomele/ssl_cert.pem,/home/sta/ristomele/ssl_key.pem

vacuum = true
die-on-term = true
