"""
Standalone server-side menu definitions
"""


def _item(name, price, is_drink=False):
    return {'kind': 'item', 'name': name, 'price': price, 'is_drink': is_drink}


def _drink(name, price):
    return _item(name, price, is_drink=True)


def _foc(name, price):
    return _item('Foc. ' + name, price)


def _sep(name):
    return {'kind': 'separator', 'name': name, 'price': 0, 'is_drink': False}


def get_menu():
    # REMEMBER TO CHANGE config.MODE between 'sagra' and 'ristorante'
    # in server/config.py
    #
    #return menu_13_agosto()
    #return menu_14_agosto()
    return menu_sagra()
    #return menu_croce()


def menu_croce():
    return [
        _item('Coperto', 1.5),
        _sep('Primi'),
        _item('Pansoti salsa di noci', 7),
        _item('Pansoti burro e salvia', 6),
        _item('Trenette al pesto', 6),
        _sep('Secondi'),
        _item('Arrosticini maiale', 5),
        _item('Arrosticini pollo', 5),
        _item('Arrosticini pecora', 6),
        _item('Arrosticini misti', 5),
        _item('Salsiccia', 5),
        _item('Coppa', 4),
        _item('Tondini Bosc.', 7),
        _sep('Contorni'),
        _item('Patatine', 2.5),
        _item('Pomodori', 1.5),
        _item('Frisceu', 2),
        _sep('Dolci'),
        _item('Crepes nutella', 3.5),
        _item('Crepes marmellata', 3.5),
        _item('Dolci misti', 2.5),
        _sep('Bibite'),
        _drink('Acqua Nat.', 1),
        _drink('Acqua Friz.', 1),
        _drink('Coca cola', 2),
        _drink('Coca Zero', 2),
        _drink('Fanta', 2),
        _drink('Sprite', 2),
        _drink('Estathe Limone', 2),
        _drink('Estathe Pesca', 2),
        _sep('Vino'),
        _drink('Barbera', 6),
        _drink('Bonarda', 5),
        _drink('Dolcetto', 5),
        _drink('Chardonney Fermo', 5),
        _drink('Chardonney Frizz', 5),
        _drink('Sangria', 4),
        _drink('Bicch. Vino', 1),
        _sep('Birre'),
        _drink('Birra IPA rossa', 4.5),
        _drink('Birra PILS', 4.5),
        _sep('Altro'),
        _item('Caffe', 1),
        _item('Crema caffe', 2.5),
        _item('Camatti', 2),
        _item('Granite', 2.5),
        _item('Sorbetto limone', 2.5),
    ]


def menu_sagra():
    return [
        _sep('Focaccini'),
        _foc('Zeneize de Me', 2),
        _foc('Zeneize de Me + zucchero', 2),
        _foc('Boscaiolo e cotto', 5.5),
        _foc('Boscaiolo e crudo', 5.5),
        _foc('Boscaiolo e speck', 5.5),
        _foc('Brie e miele', 4),
        _foc('Cotto', 4),
        _foc('Cotto e pistacchio', 5),
        _foc('Cotto e stracchino', 5),
        _foc('Cotto, stracchino e pistacchio', 6),
        _foc('Crema di carciofi', 4),
        _foc('Crema di carciofi e cotto', 5),
        _foc('Crema di carciofi e crudo', 5),
        _foc('Crema di carciofi e salame', 5),
        _foc('Crema di carciofi e salame piccante', 5),
        _foc('Crema di carciofi e speck', 5),
        _foc('Crudo', 4),
        _foc('Crudo e pistacchio', 5),
        _foc('Crudo e stracchino', 5),
        _foc('Crudo, stracchino e pistacchio', 6),
        _foc('Gorgonzola', 4),
        _foc('Gorgonzola e noci', 5),
        _foc('Gorgonzola e pistacchio', 5),
        _foc('Gorgonzola, miele e noci', 5),
        _foc('Pesto', 4),
        _foc('Pesto e stracchino', 5),
        _foc('Porchetta', 5),
        _foc('Porchetta e cipolle', 5.5),
        _foc('Porchetta e pistacchio', 6),
        _foc('Salame', 4),
        _foc('Salame piccante', 4),
        _foc('Salame piccante e gorgo', 5),
        _foc('Salame picc. e stracchino', 5),
        _foc('Salsiccia', 5),
        _foc('Salsiccia e cipolle', 5.5),
        _foc('Speck', 4),
        _foc('Speck e brie', 5),
        _foc('Speck e pistacchio', 5),
        _foc('Speck, brie e pistacchio', 6),
        _foc('Stracchino', 4),
        _foc('Stracchino e pistacchio', 5),
        _foc('Crema al Pistacchio', 5),
        _foc('Nutella', 4),
        _sep('Focaccini Speciali del Giorno'),
        _foc('VENERDI - Pancetta+peperoni', 6.5),
        _foc('SABATO - Mort+pist+burratina', 6.5),
        _foc('DOMENICA - Fesa tacch.+salsa tonn', 6.5),
        _sep('Alla piastra'),
        _item('Salsiccia', 4.5),
        _item('Salsiccia e patatine', 5.5),
        _item('Porchetta', 4.5),
        _item('Porchetta e patatine', 5.5),
        _item('Patate fritte', 3),
        _sep('BAR'),
        _drink('ECO-Bicchiere', 1),
        _drink('Bicchiere Piccolo Vino', 1.5),
        _drink('Bicchiere Grande Vino', 3),
        _drink('Birra artigianale PILS **', 5),
        _drink('Birra artigianale WEISS **', 5),
        _drink('Sangria **', 5),
        _drink('Spritz **', 5),
        _drink('Acqua minerale 0.50L', 1),
        _drink('Coca Cola **', 2),
        _drink('Fanta **', 2),
        _drink('Gazzosa **', 2),
        _drink('THE Limone **', 2),
        _drink('THE Pesca **', 2),
        _drink('Amaro Camatti', 3),
        _drink('Liquore Liquirizia', 3),
        _drink('Caffe', 1),
    ]


def menu_13_agosto():
    return [
        _sep('Focaccini'),
        _foc('Zeneize de Me', 2),
        _foc('Zeneize + zucchero', 2),
        _foc('Boscaiolo + cotto', 5.5),
        _foc('Boscaiolo + crudo', 5.5),
        _foc('Cotto', 4),
        _foc('Cotto + pistacchio', 5),
        _foc('Cotto + stracchino', 5),
        _foc('Cotto + stracch + pist', 6),
        _foc('Carciofi', 4),
        _foc('Carciofi + cotto', 5),
        _foc('Carciofi + crudo', 5),
        _foc('Carciofi + salame', 5),
        _foc('Carciofi + salam picc', 5),
        _foc('Crudo', 4),
        _foc('Crudo + pistacchio', 5),
        _foc('Crudo + stracchino', 5),
        _foc('Crudo + stra + pist', 6),
        _foc('Tacchino + tonnata', 6),
        _foc('Porchetta', 5),
        _foc('Porchetta + pistacchio', 6),
        _foc('Salame', 4),
        _foc('Salame + stracchino', 5),
        _foc('Salam picc', 4),
        _foc('Salam picc + stracchino', 5),
        _foc('Salsiccia', 5),
        _foc('Stracchino', 4),
        _foc('Stracchino + pistacchio', 5),
        _foc('Pistacchio dolce', 5),
        _foc('Nutella', 4),
        _sep('Alla piastra'),
        _item('Salsiccia piastra', 4.5),
        _item('Salsiccia + patatine', 5.5),
        _item('Porchetta piastra', 4.5),
        _item('Porchetta + patatine', 5.5),
        _item('Patatine fritte', 3),
        _sep('Vino'),
        _drink('Bicchiere piccolo rosso', 1.5),
        _drink('Bicchiere piccolo bianco', 1.5),
        _drink('Bicchiere grande rosso', 3),
        _drink('Bicchiere grande bianco', 3),
        _sep('Altre bevande'),
        _drink('Sangria', 5),
        _drink('Spritz', 5),
        _drink('Birra PILS', 5),
        _drink('Birra WEISS', 5),
        _drink('Coca Cola', 2),
        _drink('Fanta', 2),
        _drink('Gazzosa', 2),
        _drink('The Limone', 2),
        _drink('The Pesca', 2),
        _drink('Acqua naturale 0.5L', 1),
        _drink('Acqua frizzante 0.5L', 1),
        _drink('Amaro camatti', 3),
        _drink('Liquore liquirizia', 3),
        _drink('Caffe', 1),
    ]


def menu_14_agosto():
    return [
        _item('Coperto', 1.5),
        _sep('Primi'),
        _item('Ravioli au Tuccu', 8),
        _item('Trenette al pesto', 6.5),
        _sep('Secondi'),
        _item('Salsiccia', 4.5),
        _item('Salsiccia + patatine', 5.5),
        _item('Salsiccia + ins peperoni', 5.5),
        _item('Salsiccia + pomodori', 5.5),
        _item('Porchetta', 4.5),
        _item('Porchetta + patatine', 5.5),
        _item('Porchetta + ins peperoni', 5.5),
        _item('Porchetta + pomodori', 5.5),
        _item('Arrosto', 5),
        _item('Arrosto + patatine', 6),
        _item('Arrosto + ins peperoni', 6),
        _item('Arrosto + pomodori', 6),
        _sep('Contorni'),
        _item('Patatine fritte', 3),
        _item('Insalata di peperoni', 3),
        _item('Pomodori', 2),
        _sep('Dolci'),
        _item('Panna cotta caramello', 3),
        _item('Panna cotta cioccolato', 3),
        _item('Panna cotta frutti di bosco', 3),
        _item('Sorbetto al limone', 3),
        _item('Tartufo bianco', 3),
        _item('Tartufo cioccolato', 3),
        _sep('Vino'),
        _drink('Bicchiere piccolo dolcetto', 1.5),
        _drink('Bicchiere piccolo bonarda', 1.5),
        _drink('Bicchiere piccolo bianco', 1.5),
        _drink('Bicchiere grande dolcetto', 3),
        _drink('Bicchiere grande bonarda', 3),
        _drink('Bicchiere grande bianco', 3),
        _drink('Bottiglia vino dolcetto', 8),
        _drink('Bottiglia vino bonarda', 8),
        _drink('Bottiglia vino bianco', 8),
        _sep('Altre bevande'),
        _drink('Sangria', 5),
        _drink('Spritz', 5),
        _drink('Birra alla spina PILS', 5),
        _drink('Birra alla spina WEISS', 5),
        _drink('Coca Cola', 2),
        _drink('Aranciata', 2),
        _drink('Gazzosa', 2),
        _drink('The Limone', 2),
        _drink('The Pesca', 2),
        _drink('Acqua naturale 0.5L', 1),
        _drink('Acqua frizzante 0.5L', 1),
        _drink('Amaro camatti', 3),
        _drink('Liquore liquirizia', 3),
        _drink('Caffe', 1),
    ]
